### ISSUE TITLE
Very simple path throws error

### ISSUE THREAD

**Issue by HerrZatacke** [fracalo/svg-contour#1]
I was adding the following path to `example/index.html` and experienced an error:
`Uncaught Error: parallel lines don't intersect`
The path in question: (I simplified it from a complex path down to the bare minimum)

```xml
<path id="flat" d=" M163.095 78.262 L163.212 78.711 L163.328 79.160" stroke-width="0.3" stroke="#000" fill="none" />
```

Do you have any Idea why this is happening? Or can you recommend another Library which performs the same task (I could not find anything else working 😞 but your library is _exactly_ what I'd need)

**Comment by fracalo** [comment]
Hey, nice to know somebody is still using this, lets see if I can help you out!

The macro view of the `svgContour` function is:
1. it transforms the segments between each point in lines (in case of a curve this is first divided in segments).
2. the lines are offset by a certain amount defined in the [config](https://github.com/fracalo/svg-contour/blob/master/example/example-app.js#L5) `offset` field.
3. the intersection between lines is used in order to create the new path.

The error you're seeing is being thrown from [here](https://github.com/fracalo/svg-contour/blob/master/src/utils/Line.js#L50-L53) because when we calculate the intersection between the 2 lines produced by the 3 points the `m` (aka [slope-interceptor](https://www.mathcentre.ac.uk/resources/uploaded/mc-bus-slope-2009-1.pdf)) value is the same.

The main problem i see with the path provided is that the points are too close to each other. 
This, and the binary floating-point arithmetic rounding imprecision, are the culprit of the error.

You can notice that just by opening up the points a little the error is avoided and the contour gets drawn.
```svg
<path id="flat" d=" M163.095 79 L163.212 78.711 L164 79.160" stroke-width="0.3" stroke="#000" fill="none" />
```
---
Generally speaking this library served me well when i created it some years back but I haven't used it in a while, and, if I was to get back to it, there are surely things I would improve.
At the time I built it there was nothing similar, but I don't know if there are any alternatives nowadays.

I don't have much details of what you're doing so its hard giving suggestions, but in the past i have sometimes dealt with floating number math precision issues transforming everything to integer. 

Let me know how it goes, and if you eventually decide that there is no better alternative and want to bring this library back to life just start proposing changes, I'll be happy to help out.

**Comment by HerrZatacke** [comment]
Hi,

thanks for your response. 
My task is to create a path outline (which can be filled) from a path which is just displayed through the stroke/stroke-width attributes.

I meanwhile tried to implement the same thing and during that encountered a similar issue.

After that I changed my approach and used `path.getTotalLength()`  and `path.getPointAtLength(pos)` which for my use-case is "good enough"

Shortly after that my whole implementation became kinda obsolete... So I probably won't follow that approach...

Still your response is highly appreciated. Thank you!

<sub>It's really funny though that modern vector software (including inkscape) have a funtion to perform this task, yet I have not found any fully working JS implementation</sub>

**Comment by fracalo** [comment]
> It's really funny though that modern vector software (including inkscape) have a funtion to perform this task, yet I have not found any fully working JS implementation

I'd go even further and say it should be part of the `svg` specs, embedded in the browser native implementation
